#pragma once
#include <cstdint>
struct PerTerrainCB
{
    int grid_dim_x;
    int grid_dim_y;
    float min_x;
    float max_x;
    float min_y;
    float max_y;
    float min_z;
    float max_z;
    float water_level;
    float terrain_texture_pad_x;
    float terrain_texture_pad_y;
    float water_distortion_tex_scale;
    float water_distortion_scale;
    float water_distortion_tex_speed;
    float water_color_tex_scale;
    float water_color_tex_speed;
    float water_fresnel;
    float water_specular_scale;
    uint32_t water_technique;
    float water_runtime_param_28;
    DirectX::XMFLOAT4 color0;
    DirectX::XMFLOAT4 color1;
    float water_flow_dir[2];
    float water_flow_padding[2];
};
