#ifndef RENDER_CONSTANTS_H
#define RENDER_CONSTANTS_H

#define PER_FRAME_CB_SLOT 0
#define PER_OBJECT_CB_SLOT 1
#define PER_CAMERA_CB_SLOT 2
#define PER_TERRAIN_CB_SLOT 3

#endif // RENDER_CONSTANTS_H
